site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://os.haohaha.cn/image/favicon.png
  palette:
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh

nav:
  - 主页: http://haohaha.cn
  - CS笔记: http://cs.haohaha.cn
  - 闲聊波尔卡: http://chat.haohaha.cn 
  - OS学习: 
    - Home: index.md
    - uCore 笔记: 
      - ucore/notes/index.md
      - Lab3 虚拟内存管理: ucore/notes/lab3.md
    - rCore 笔记:
      - rcore/notes/index.md
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://haohaha.cn
  ## [bottom-right corner]
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/chat/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: Copyright &copy; 2022 浩哈哈哈哈_ # 左下角的版权声明

